# Autogenerated wrapper script for libcbor_jll for aarch64-apple-darwin
export libcbor

JLLWrappers.@generate_wrapper_header("libcbor")
JLLWrappers.@declare_library_product(libcbor, "@rpath/libcbor.0.12.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcbor,
        "lib/libcbor.0.12.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
