# Autogenerated wrapper script for libcbor_jll for i686-w64-mingw32
export libcbor

JLLWrappers.@generate_wrapper_header("libcbor")
JLLWrappers.@declare_library_product(libcbor, "libcbor.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcbor,
        "bin\\libcbor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
