# Autogenerated wrapper script for libcbor_jll for riscv64-linux-gnu
export libcbor

JLLWrappers.@generate_wrapper_header("libcbor")
JLLWrappers.@declare_library_product(libcbor, "libcbor.so.0.12")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcbor,
        "lib/libcbor.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
